-- USER SQL
ALTER USER "carroFeliz"
DEFAULT TABLESPACE "SYSTEM"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "carroFeliz" DEFAULT ROLE "CONNECT";



--TABLAS
 CREATE TABLE "carroFeliz"."CARRO" 
   (	"PLACA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COLOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CILINDRAJE" NUMBER NOT NULL ENABLE, 
	"MODELO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "CARRO_PK" PRIMARY KEY ("PLACA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
   CREATE TABLE "carroFeliz"."CARROCOMPRADOR" 
   (	"PLACAA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDE_COMPRADOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CARROCOMPRADOR_PK" PRIMARY KEY ("PLACAA", "IDE_COMPRADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  

  CREATE TABLE "carroFeliz"."CARROVENDEDOR" 
   (	"PLAQUITA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDE_VENDEDOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CARROVENDEDOR_PK" PRIMARY KEY ("PLAQUITA", "IDE_VENDEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  CREATE TABLE "carroFeliz"."COMPRADOR" 
   (	"ID_COMPRADOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMBRE_COMPRADOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TELEFONO_COMPRADOR" NUMBER NOT NULL ENABLE, 
	"CORREO_COMPRADOR" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "COMPRADOR_PK" PRIMARY KEY ("ID_COMPRADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "carroFeliz"."VENDEDOR" 
   (	"ID_VENDEDOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMBRE_VENDEDOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TELEFONO_VENDEDOR" NUMBER NOT NULL ENABLE, 
	"CORREO_VENDEDOR" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "VENDEDOR_PK" PRIMARY KEY ("ID_VENDEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

